sudo: required
language: cpp
services:
    - docker

notifications:
  email: false

env:
  global:
      - secure: sv19elMDeQz6I/LeXzwZ8t2s7UnW8r3gLwEqzUrpMOuV5tZnroQQ9T+oX/QAT7f6bPgq124EzKPt42bYh+3Ls8DHv4cIJJCXihw8xwkR5sPYsj3VUEpw/K2JyImNc+W3F+MsV5IqGATUQmG/5zYo3IXzlM+Z85cp5omk1oAfJR+CimGsFXwFyUt3s87F82UNW0CV7UplWFpKFuAhnlKx77TEMP2PqJK2bBLuNz22Aw3N2va60L+sykWOLS+tp9hpOC0jRSmbIy57ltsbz0k9bVfQg1VKaGlHC649qyY/9L8vC9sAsvF5j42+HtRK/7V3cUhlU9sVSWD21kCAWkcnmRTeseonq/zorLeYf530CCyUGROXDJ6tG7/YtFYL5+v/fSkLmdegjZDwNYxbvVB1+NvXUrcQKJTrRwFHrRf4sefqpqh9qU2TSWtsRjGv46zNz7hJhSAzW/6KrGm+jVE2PrlzfpyW8u3Y8H0VTX2gdcMq/wLm7FPhPeWbWRUyFiCqGDbEhjOrnI2LBgwAeYQDFQNh2ooxKPrnKw1wlcPiQCNNT1/CARvHGaVHYXDDJhi3O7hCwcqecmt+k27r+jn2l0wZK2fkkGb6ESmK7UJOAZX/CKpSV1F5c+El+jlykl3zq+8x+2fknFg7KH0KQpunhSo1BvvOGBRmqS/JEOvxhGo=
      - secure: FHlmfo3UTQwvOwispfqIvPQcvrCzNifGxfJn/dVuh15LLiFWVBsuXJp18lTKJQOd9coQ8KQzg+kTWC2RjYSb6LQRrpaG/hLXBhiP9UzYk4a61dU06vMhDtf8T0mjDIGF8ZYUsNmY0rZ5K7eWs6PDm/II4700njFQOUH4FbB+mJybBflWwERWmo8UaIS5EqcDaBRUxQ2dIqaRIxWeLHLiRHldPURD3KTGaVNgT/P/zHzgCDQAGBSGYLMI8YmfJxDoniW8KtHavxJrhlBm+Qrr7x3aFBobe6Bqmy7cx3F9WaS7kFzfuO63f9rby7+gNSnMdAOyOO0eaCF8cP261bqVZDHVXJ9GwtG4t1hQkbaUf1MEeB6SBKkQ5Ww9y2bWhP2xIIxpOzBIX/UdeUV+6lFQhquhzRmNu5f7Opv5AyU9xnLp+QBXpgaO80bqX39Jfdg4eE4CQ9xJgHfsnDFNh8fh7CQvHt/3HHwwpLQ7ZK7NQAw9BD53hkTMrqRaOutvESVZGrBwObhNIur2cm3DFNxZPz+efVb/nJbHkZb7ifFmyypqLj4y7X2KCmKxjniiBiljQKEgfO6Sytxh/5/ProeK0E5D/Vqkosb7U7hoOBljzfu6ay0VBPqM2tC+MJ6yA+s+tU3jQfDVDJho545rM2eVHxrgJ2n7QL5dCTkwl4hKOCo=

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-5 g++-5 -y && CC=gcc-5 && CXX=g++-5
  - sudo apt-get install -y libzmq3-dev
  - git clone --branch v1.8.0 https://github.com/google/flatbuffers.git && cd flatbuffers && cmake -G "Unix Makefiles" && sudo make install && cd ..
  - git clone --branch 0.4.0 https://github.com/QuantStack/xtl.git && cd xtl && cmake . && sudo make install && cd ..
  - git clone --branch 0.15.4 https://github.com/QuantStack/xtensor.git && cd xtensor && cmake . && sudo make install && cd ..

script:
  - mkdir build && cd build
  - cmake ../src
  - cmake --build .

after_success:
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
          GIT_COMMIT="$(git rev-parse HEAD)" ;
          echo $GIT_COMMIT ;
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
          docker build -t probprog/cpproblight --build-arg GIT_COMMIT=$GIT_COMMIT . ;
          docker tag probprog/cpproblight probprog/cpproblight:latest ;
          docker push probprog/cpproblight:latest ;
          if [[ -n "$TRAVIS_TAG" ]]; then
            docker tag probprog/cpproblight probprog/cpproblight:$TRAVIS_TAG ;
            docker push probprog/cpproblight:$TRAVIS_TAG ;
          fi
      fi
