sudo: required
language: cpp
services:
    - docker

notifications:
  email: false

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-5 g++-5 -y && CC=gcc-5 && CXX=g++-5
  - sudo apt-get install -y libzmq3-dev
  - git clone --branch v1.8.0 https://github.com/google/flatbuffers.git && cd flatbuffers && cmake -G "Unix Makefiles" && sudo make install && cd ..
  - git clone --branch 0.4.0 https://github.com/QuantStack/xtl.git && cd xtl && cmake . && sudo make install && cd ..
  - git clone --branch 0.15.4 https://github.com/QuantStack/xtensor.git && cd xtensor && cmake . && sudo make install && cd ..

script:
  - mkdir build && cd build
  - cmake ../src
  - cmake --build .
  - sudo make install
  - cd ..

after_success:
  - export CURRENT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, CURRENT_BRANCH=$CURRENT_BRANCH"
  - echo "TRAVIS_TAG=$TRAVIS_TAG"
  - if [[ "$CURRENT_BRANCH" == "master" ]] || [[ -n "$TRAVIS_TAG" ]]; then
      GIT_COMMIT="$(git rev-parse HEAD)" ;
      echo $GIT_COMMIT ;
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker build -t probprog/cpproblight --build-arg GIT_COMMIT=$GIT_COMMIT . ;
      docker tag probprog/cpproblight probprog/cpproblight:latest ;
      docker push probprog/cpproblight:latest ;
      if [[ -n "$TRAVIS_TAG" ]]; then
        docker tag probprog/cpproblight probprog/cpproblight:$TRAVIS_TAG ;
        docker push probprog/cpproblight:$TRAVIS_TAG ;
      fi
    fi
