sudo: required
language: cpp

install:
  - sudo apt-get install -y libzmq3-dev
  - git clone --branch 0.4.0 https://github.com/QuantStack/xtl.git && cd xtl && cmake . && sudo make install && cd ..

script:
  - mkdir build && cd build
  - cmake ../src
  - cmake --build .
